(function() {var implementors = {};
implementors["search_graph"] = [{text:"impl&lt;'a, 'id, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>, S, A&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/index/trait.Index.html\" title=\"trait core::ops::index::Index\">Index</a>&lt;<a class=\"struct\" href=\"search_graph/view/struct.NodeRef.html\" title=\"struct search_graph::view::NodeRef\">NodeRef</a>&lt;'id&gt;&gt; for <a class=\"struct\" href=\"search_graph/view/struct.View.html\" title=\"struct search_graph::view::View\">View</a>&lt;'a, 'id, T, S, A&gt;",synthetic:false,types:["search_graph::view::View"]},{text:"impl&lt;'a, 'id, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>, S, A&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/index/trait.Index.html\" title=\"trait core::ops::index::Index\">Index</a>&lt;<a class=\"struct\" href=\"search_graph/view/struct.EdgeRef.html\" title=\"struct search_graph::view::EdgeRef\">EdgeRef</a>&lt;'id&gt;&gt; for <a class=\"struct\" href=\"search_graph/view/struct.View.html\" title=\"struct search_graph::view::View\">View</a>&lt;'a, 'id, T, S, A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;'a: 'id,&nbsp;</span>",synthetic:false,types:["search_graph::view::View"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
